import Head from 'next/head'
import Header from '@/components/Header'
import Cards from '@/components/Cards'
import { GetServerSideProps, NextPage } from 'next'
import { Movie } from '@/models'
import { Context } from '../../context'
import { useState } from 'react'

interface Movies {
  movies: Movie[]
}

const Home: NextPage<Movies> = ({ movies }) => {

  const [userInput, setUserInput] = useState<string>('')

  return (
    <Context.Provider value={{ userInput, setUserInput }}>

      <main className='space-y-72'>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <h1 className='text-center font-black text-9xl italic'>Discover</h1>

        <Cards userInput={userInput} movies={movies} />

      </main>
    </Context.Provider>
  )
}

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://yts.mx/api/v2/list_movies.json')
  const data = await res.json()

  return {
    props: {
      movies: data.data.movies
    }
  }
}