import Head from 'next/head'
import { GetServerSideProps, NextPage } from 'next'
import { Movie } from '@/models'
import Image from 'next/image'
import { ChangeEvent, useState } from 'react'
import { FilmIcon } from '@heroicons/react/24/outline'
import { useRouter } from 'next/router'
interface Movies {
  movies: Movie[]
}

const Home: NextPage<Movies> = ({ movies }) => {

  const [userInput, setUserInput] = useState<string>('')

  const inputHandler = (e: ChangeEvent<HTMLInputElement>) => {
    setUserInput(e.target.value)
  }

  const router = useRouter()

  const searchTerms = () => { }

  return (
    <main className='space-y-72'>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <nav className='flex items-center justify-between'>
          <FilmIcon className='h-8 animate-pulse cursor-pointer' onClick={() => router.push('/')} />

          <input type="text" className='outline-none px-4 py-2 rounded-lg bg-[#141414] w-1/5' placeholder='Search movie' onChange={inputHandler} />

          <button className='bg-white border text-black transition duration-150 rounded-md px-6 py-2 hover:bg-black hover:text-white font-light hover:border'>Log in</button>
        </nav>
      </section>

      <h1 className='text-center font-black text-9xl italic'>Discover</h1>

      <div className='grid grid-cols-4 gap-10 bg-[#222222] px-10 py-8 rounded-t-xl'>
        {movies.filter((item) => { return userInput.toLowerCase() === '' ? item : item.title.toLowerCase().includes(userInput) }).map(({ id, title, year, rating, large_cover_image }) => (
          <div key={id} className="space-y-5">
            <Image onClick={searchTerms} src={large_cover_image} alt="cover_img" width={400} height={400} className="rounded-xl transition duration-100 hover:scale-90 cursor-pointer hover:opacity-75" />
            <h3 className='text-3xl font-bold'>{title}</h3>
            <div className='flex gap-5'>
              <p className='text-[#c0c0c0] text-lg'>{year}</p>
              <span className='font-bold text-emerald-500'>|</span>
              <p className='text-[#c0c0c0] text-lg'>{rating}</p>
            </div>
          </div>
        ))}
      </div>

    </main>
  )
}

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('https://yts.mx/api/v2/list_movies.json')
  const data = await res.json()

  return {
    props: {
      movies: data.data.movies
    }
  }
}